"""
MT5 Forex Trading Configuration — re-exports from root config.py for backward compatibility.
All settings are now centralized in the root config.py file.
Single-user mode with hardcoded MT5 credentials from local terminal.
"""
from config import (
    MT5_SERVER,
    MT5_FOREX_SYMBOLS as FOREX_SYMBOLS,
    MT5_LOT_SIZE as LOT_SIZE,
    MT5_MAX_CONCURRENT_TRADES as MAX_CONCURRENT_TRADES,
    MT5_MAGIC_NUMBER as MAGIC_NUMBER,
    MT5_WIN_PERCENTAGE as WIN_PERCENTAGE,
    MT5_LOSS_PERCENTAGE as LOSS_PERCENTAGE,
    MT5_TAKE_PROFIT_PIPS as TAKE_PROFIT_PIPS,
    MT5_STOP_LOSS_PIPS as STOP_LOSS_PIPS,
    MT5_BREAKEVEN_TRIGGER_PCT as BREAKEVEN_TRIGGER_PCT,
    MT5_TRAILING_TRIGGER_PCT as TRAILING_TRIGGER_PCT,
    MT5_TRAILING_STOP_PCT as TRAILING_STOP_PCT,
    MT5_DEVIATION as DEVIATION,
    MT5_SIGNAL_TIMEFRAME as SIGNAL_TIMEFRAME,
    MT5_TREND_TIMEFRAME as TREND_TIMEFRAME,
    MT5_SUPPORT_RESISTANCE_TIMEFRAME as SUPPORT_RESISTANCE_TIMEFRAME,
    MT5_STOCH_RSI_PERIOD as STOCH_RSI_PERIOD,
    MT5_STOCH_K_SMOOTH as STOCH_K_SMOOTH,
    MT5_STOCH_D_SMOOTH as STOCH_D_SMOOTH,
    MT5_RSI_PERIOD as RSI_PERIOD,
    MT5_STOCH_RSI_SHORT_LEVEL as STOCH_RSI_SHORT_LEVEL,
    MT5_STOCH_RSI_BUY_LEVEL as STOCH_RSI_BUY_LEVEL,
    MT5_MIN_SIGNAL_SCORE as MIN_SIGNAL_SCORE,
    MT5_CANDLES_FOR_ANALYSIS as CANDLES_FOR_ANALYSIS,
    MT5_SCAN_INTERVAL_SECONDS as SCAN_INTERVAL_SECONDS,
    MT5_SLEEP_BETWEEN_SYMBOLS as SLEEP_BETWEEN_SYMBOLS,
)

# Single-user mode: MT5_SERVER is hardcoded in config.py
